services:

  # Base de données MySQL
  db:
    image: mysql:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mmi-archive-db
    restart: always
    environment:
      MYSQL_DATABASE: mmi-archive
      MYSQL_ROOT_PASSWORD: mmi-archive
      MYSQL_PASSWORD: mmi-archive
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      retries: 10
      timeout: 5s

  # API Spring Boot 
  api:
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile
    container_name: mmi-archive-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mmi-archive
      SPRING_DATASOURCE_PASSWORD: mmi-archive
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: 
